name: Run tests and upload coverage

on: 
  push

permissions:
  contents: write
  checks: write
  actions: write
  deployments: write


jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pytest coverage

      - name: Delete existing coverage file
        run: rm -rf test_coverage.svg
        
      - name: Run tests
        run: coverage run -m pytest

      - name: Upload coverage result to test_coverage.svg
        run: python coverage.py -o test_coverage.svg
